# Generated by Django 4.2.7 on 2023-11-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profil_tasdiqlangan_profil_tasdiqlsh_kodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='tasdiqlsh_kodi',
            new_name='tasdiqlash_kodi',
        ),
    ]
